import os
from urllib.request import Request, urlopen
from urllib.error import HTTPError, URLError
import json


GITHUB_API = "https://api.github.com"


def get_github_token() -> str:

    token = os.getenv("GITHUB_TOKEN")

    if not token:
        raise RuntimeError(
            "GITHUB_TOKEN environment variable is not configured."
        )

    return token


def get_repo_info() -> tuple[str, str]:

    repository = os.getenv("GITHUB_REPOSITORY")

    if not repository:
        raise RuntimeError(
            "GITHUB_REPOSITORY environment variable is not configured."
        )

    try:
        owner, repo = repository.split("/", 1)

    except ValueError as exc:

        raise RuntimeError(
            "GITHUB_REPOSITORY must be in the format: "
            "owner/repository"
        ) from exc

    return owner, repo


def github_request(
    method: str,
    path: str,
    body: dict | None = None,
) -> dict:

    token = get_github_token()

    url = f"{GITHUB_API}{path}"

    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2026-03-10",
        "Content-Type": "application/json",
        "User-Agent": "ai-documentation-agent",
    }

    data = None

    if body is not None:
        data = json.dumps(body).encode("utf-8")

    request = Request(
        url=url,
        method=method,
        headers=headers,
        data=data,
    )

    try:

        with urlopen(request) as response:

            response_body = response.read()

            if not response_body:
                return {}

            return json.loads(
                response_body.decode("utf-8")
            )

    except HTTPError as exc:

        error_body = exc.read().decode(
            "utf-8",
            errors="replace",
        )

        raise RuntimeError(
            f"GitHub API error {exc.code}: "
            f"{error_body}"
        ) from exc

    except URLError as exc:

        raise RuntimeError(
            f"Unable to connect to GitHub: {exc}"
        ) from exc


def create_pull_request(
    branch_name: str,
    commit_sha: str,
) -> dict:

    owner, repo = get_repo_info()

    title = (
        f"docs: update SD and DD for "
        f"{commit_sha[:8]}"
    )

    body = f"""## AI Documentation Update

Generated from:
- Main commit: `{commit_sha}`

### Documentation Updated

- `docs/SD.md`
- `docs/DD.md`

### Review Required

Please verify the generated documentation against
the source code changes.

Generated by Jenkins + Gemini.
"""

    return github_request(
        "POST",
        f"/repos/{owner}/{repo}/pulls",
        {
            "title": title,
            "body": body,
            "head": branch_name,
            "base": "main",
        },
    )